/* Copyright 2011 www.sugawara-systems.com
 * Note:
 * This file is automatically generated.
 * Please do not edit this file - you will lose your edits.*/

#define DPI_COMPATIBILITY_VERSION_1800v2012

#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL extern "C"
#else
#define DPI_LINK_DECL
#endif

#include "svdpi.h"

typedef struct {
  char red;
  char green;
  char blue;
} RGB_TYPE;

DPI_LINK_DECL DPI_DLLESPEC
void set_fixed1(RGB_TYPE*);

DPI_LINK_DECL DPI_DLLESPEC
void set_fixed2(RGB_TYPE*);

DPI_LINK_DECL DPI_DLLESPEC
void set_fixed3(RGB_TYPE*);

#endif
